site_name: Jaras

nav:
- About: about.md
- Home: index.md
#add repo here d
- example-repo: docs/.github/workflows/README.md

plugins:
- search:
    lang:
    - ar
    - en
theme:
  features:
  - search.suggest
  - search.highlight
  - search.share
  language: ar
  name: readthedocs
  palette:
  - accent: indigo
    primary: indigo
    scheme: default
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - accent: blue
    primary: blue
    scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode



